modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Hipposgrumm/armor-trims/issues"

[[mods]]
modId="armor_trims"
version="${file.jarVersion}"
displayName="Armor Trims"
logoFile="mod.png"
credits="Intellij IDEA, Trims by Mojang Studios - Ported by Hipposgrumm"
authors="Hipposgrumm"
description='''
Backported the Armor Trims from 1.20.

Is this mod a little too configurable? I feel like it's a little too configurable.
'''

[[dependencies.armor_trims]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.armor_trims]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.armor_trims]]
    modId="jei"
    mandatory=false
    versionRange="[9.6.0,)"
    ordering="AFTER"
    side="CLIENT"
