modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="${license}"
issueTrackerURL="https://github.com/Hipposgrumm/armor-trims/issues"

[[mods]]
modId="${modid}"
version="${version}"
displayName="${mod_name}"
logoFile="${modid}.png"
credits="Armor Trim textures and Color Palettes are taken directly from the Minecraft assets"
authors="${author}"
description='''${mod_description}'''

[[dependencies.${modid}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_dep}"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="jei"
mandatory=false
versionRange="[${jei_rei_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${modid}]]
modId="cloth_config"
mandatory=false
versionRange="[${cloth_version},)"
ordering="BEFORE"
side="CLIENT"